run:
  go: '1.18.4'

output:
  format: colored-line-number

linters-settings:
  revive:
    max-open-files: 2048
    ignore-generated-header: true
    severity: error
    rules:
      - name: add-constant
        severity: warning
        disabled: false
        arguments:
          - maxLitCount: "4"
            allowStrs: '""'
            allowInts: "0,1,2,3,4,5,6,7,8,9"
            allowFloats: "0.0,0.,1.0,1.,2.0,2."

      - name: defer
        severity: warning
        disabled: false
        arguments:
          - ["call-chain", "loop"] 

      - name: line-length-limit
        severity: warning
        disabled: false
        arguments: [120]

      - name: modifies-parameter
        severity: warning
        disabled: false

      - name: nested-structs
        severity: warning
        disabled: false

      - name: receiver-naming
        severity: warning
        disabled: false

      - name: redefines-builtin-id
        severity: warning
        disabled: false

      - name: unnecessary-stmt
        severity: warning
        disabled: false

      - name: useless-break
        severity: warning
        disabled: false

      - name: error-naming
        severity: warning
        disabled: false

      - name: unreachable-code
        severity: warning
        disabled: false

linters:
  disable-all: true
  enable: 
    - deadcode 
    - errcheck 
    - gosimple 
    - govet 
    - ineffassign 
    - staticcheck 
    - typecheck 
    - unused 
    - varcheck 
    - gocyclo 
    - goconst 
    - gofumpt 
    - goimports 
    - unconvert 
    - gci
    - whitespace
    - godot
    - gosec
    - revive

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      text: "create a named constant for it"
    - path: '(.+)_test\.go'
      text: "make it a constant"
  fix: true