// Code generated by mockery v2.14.0. DO NOT EDIT.

package config

import mock "github.com/stretchr/testify/mock"

// MockMig is an autogenerated mock type for the Mig type
type MockMig struct {
	mock.Mock
}

// Dir provides a mock function with given fields:
func (_m *MockMig) Dir() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Ext provides a mock function with given fields:
func (_m *MockMig) Ext() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewMockMig interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMig creates a new instance of MockMig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMig(t mockConstructorTestingTNewMockMig) *MockMig {
	mock := &MockMig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
