// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	request "github.com/christian-gama/go-booking-api/internal/shared/presenter/http/request"
	response "github.com/christian-gama/go-booking-api/internal/shared/presenter/http/response"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// Handle provides a mock function with given fields: _a0
func (_m *Controller) Handle(_a0 *request.Request) *response.Response {
	ret := _m.Called(_a0)

	var r0 *response.Response
	if rf, ok := ret.Get(0).(func(*request.Request) *response.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.Response)
		}
	}

	return r0
}

type mockConstructorTestingTNewController interface {
	mock.TestingT
	Cleanup(func())
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewController(t mockConstructorTestingTNewController) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
