// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/christian-gama/go-booking-api/internal/domain/entity"
	error "github.com/christian-gama/go-booking-api/internal/domain/error"

	mock "github.com/stretchr/testify/mock"

	usecase "github.com/christian-gama/go-booking-api/internal/usecase"
)

// CreateRoomUsecase is an autogenerated mock type for the CreateRoomUsecase type
type CreateRoomUsecase struct {
	mock.Mock
}

// Handle provides a mock function with given fields: input
func (_m *CreateRoomUsecase) Handle(input *usecase.CreateRoomInput) (*entity.Room, []*error.Error) {
	ret := _m.Called(input)

	var r0 *entity.Room
	if rf, ok := ret.Get(0).(func(*usecase.CreateRoomInput) *entity.Room); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Room)
		}
	}

	var r1 []*error.Error
	if rf, ok := ret.Get(1).(func(*usecase.CreateRoomInput) []*error.Error); ok {
		r1 = rf(input)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*error.Error)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewCreateRoomUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewCreateRoomUsecase creates a new instance of CreateRoomUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCreateRoomUsecase(t mockConstructorTestingTNewCreateRoomUsecase) *CreateRoomUsecase {
	mock := &CreateRoomUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
