// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	errorutil "github.com/christian-gama/go-booking-api/internal/shared/domain/errorutil"
	mock "github.com/stretchr/testify/mock"
)

// DeleteRoomRepo is an autogenerated mock type for the DeleteRoomRepo type
type DeleteRoomRepo struct {
	mock.Mock
}

// DeleteRoom provides a mock function with given fields: uuid
func (_m *DeleteRoomRepo) DeleteRoom(uuid string) []*errorutil.Error {
	ret := _m.Called(uuid)

	var r0 []*errorutil.Error
	if rf, ok := ret.Get(0).(func(string) []*errorutil.Error); ok {
		r0 = rf(uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*errorutil.Error)
		}
	}

	return r0
}

type mockConstructorTestingTNewDeleteRoomRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteRoomRepo creates a new instance of DeleteRoomRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteRoomRepo(t mockConstructorTestingTNewDeleteRoomRepo) *DeleteRoomRepo {
	mock := &DeleteRoomRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
