// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/christian-gama/go-booking-api/internal/domain/entity"
	error "github.com/christian-gama/go-booking-api/internal/domain/error"

	mock "github.com/stretchr/testify/mock"
)

// GetRoomUsecase is an autogenerated mock type for the GetRoomUsecase type
type GetRoomUsecase struct {
	mock.Mock
}

// Handle provides a mock function with given fields: uuid
func (_m *GetRoomUsecase) Handle(uuid string) (*entity.Room, []*error.Error) {
	ret := _m.Called(uuid)

	var r0 *entity.Room
	if rf, ok := ret.Get(0).(func(string) *entity.Room); ok {
		r0 = rf(uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Room)
		}
	}

	var r1 []*error.Error
	if rf, ok := ret.Get(1).(func(string) []*error.Error); ok {
		r1 = rf(uuid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*error.Error)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewGetRoomUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewGetRoomUsecase creates a new instance of GetRoomUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGetRoomUsecase(t mockConstructorTestingTNewGetRoomUsecase) *GetRoomUsecase {
	mock := &GetRoomUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
