// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/christian-gama/go-booking-api/internal/room/domain/entity"
	error "github.com/christian-gama/go-booking-api/internal/shared/domain/error"

	mock "github.com/stretchr/testify/mock"
)

// ListRoomsUsecase is an autogenerated mock type for the ListRoomsUsecase type
type ListRoomsUsecase struct {
	mock.Mock
}

// Handle provides a mock function with given fields:
func (_m *ListRoomsUsecase) Handle() ([]*entity.Room, error.Errors) {
	ret := _m.Called()

	var r0 []*entity.Room
	if rf, ok := ret.Get(0).(func() []*entity.Room); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Room)
		}
	}

	var r1 error.Errors
	if rf, ok := ret.Get(1).(func() error.Errors); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(error.Errors)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewListRoomsUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewListRoomsUsecase creates a new instance of ListRoomsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewListRoomsUsecase(t mockConstructorTestingTNewListRoomsUsecase) *ListRoomsUsecase {
	mock := &ListRoomsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
