// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Mig is an autogenerated mock type for the Mig type
type Mig struct {
	mock.Mock
}

// Dir provides a mock function with given fields:
func (_m *Mig) Dir() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Ext provides a mock function with given fields:
func (_m *Mig) Ext() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewMig interface {
	mock.TestingT
	Cleanup(func())
}

// NewMig creates a new instance of Mig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMig(t mockConstructorTestingTNewMig) *Mig {
	mock := &Mig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
