// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Numbers is an autogenerated mock type for the numbers type
type Numbers struct {
	mock.Mock
}

type mockConstructorTestingTNewNumbers interface {
	mock.TestingT
	Cleanup(func())
}

// NewNumbers creates a new instance of Numbers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNumbers(t mockConstructorTestingTNewNumbers) *Numbers {
	mock := &Numbers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
