// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	request "github.com/christian-gama/go-booking-api/internal/shared/presenter/http/request"
	mock "github.com/stretchr/testify/mock"
)

// ParamReader is an autogenerated mock type for the ParamReader type
type ParamReader struct {
	mock.Mock
}

// Read provides a mock function with given fields: r, name
func (_m *ParamReader) Read(r *request.Request, name string) string {
	ret := _m.Called(r, name)

	var r0 string
	if rf, ok := ret.Get(0).(func(*request.Request, string) string); ok {
		r0 = rf(r, name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewParamReader interface {
	mock.TestingT
	Cleanup(func())
}

// NewParamReader creates a new instance of ParamReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewParamReader(t mockConstructorTestingTNewParamReader) *ParamReader {
	mock := &ParamReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
