// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/christian-gama/go-booking-api/internal/domain/entity"
	errorutil "github.com/christian-gama/go-booking-api/internal/domain/errorutil"

	mock "github.com/stretchr/testify/mock"
)

// SaveRoomRepo is an autogenerated mock type for the SaveRoomRepo type
type SaveRoomRepo struct {
	mock.Mock
}

// SaveRoom provides a mock function with given fields: room
func (_m *SaveRoomRepo) SaveRoom(room *entity.Room) (*entity.Room, []*errorutil.Error) {
	ret := _m.Called(room)

	var r0 *entity.Room
	if rf, ok := ret.Get(0).(func(*entity.Room) *entity.Room); ok {
		r0 = rf(room)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Room)
		}
	}

	var r1 []*errorutil.Error
	if rf, ok := ret.Get(1).(func(*entity.Room) []*errorutil.Error); ok {
		r1 = rf(room)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*errorutil.Error)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewSaveRoomRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewSaveRoomRepo creates a new instance of SaveRoomRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSaveRoomRepo(t mockConstructorTestingTNewSaveRoomRepo) *SaveRoomRepo {
	mock := &SaveRoomRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
