// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UUID is an autogenerated mock type for the UUID type
type UUID struct {
	mock.Mock
}

// Generate provides a mock function with given fields:
func (_m *UUID) Generate() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewUUID interface {
	mock.TestingT
	Cleanup(func())
}

// NewUUID creates a new instance of UUID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUUID(t mockConstructorTestingTNewUUID) *UUID {
	mock := &UUID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
